### ISSUE TITLE
(removed)

### ISSUE THREAD

**Issue by dmiller113** [mehcode/rn-notification#2]

**Comment by Pholey** [comment]
Ive been experiencing the same thing

**Comment by dmiller113** [comment]
As of this time it seems the npm repo is down? Did you remove it?

**Comment by Pholey** [comment]
Would you accept PRs to fix this?

**Comment by dmiller113** [comment]
![image](https://cloud.githubusercontent.com/assets/6789574/17950620/36acce18-6a11-11e6-9727-5da9ebbb5401.png)

Screenshot if it helps in fixing this.
